# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: lus_cleverreach  # Pflichtfeld
version: '1.2.0'          # Pflichtfeld
author: Laut und Schoen
supportpage: https://github.com/tyrant88/lus_cleverreach

page:
    #title: 'translate:lus_cleverreach_title'
    title: 'translate:title'
    perm: admin[]
    icon: rex-icon fa-envelope-o
    subpages:
        config: { title: 'translate:lus_cleverreach_config' }
        help: { title: 'translate:lus_cleverreach_help' }

requires:
    packages:
        yform: '>=3.1'
    redaxo: '>=5.6.0'

